### ISSUE TITLE
SumoLogic SDK fails to work

### ISSUE THREAD

**Issue by arafatmohammed** [SumoLogic/sumologic-content#23] opened 2018-04-02 16:29 UTC
Hi,

We're using Sumologic SDK (https://github.com/SumoLogic/js-logging-sdk) and get the following error:

**Failed to load https://endpoint1.collection.us2.sumologic.com/receiver/v1/http/ZaVnC4dhaV3...0SiTUGo7o9dxNm5 (index):1bJHzJr80EcmGJlbSlcdn1GYn8ooa==: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.**

Please help us fix this.

**Comment by latkin** [comment] 2018-04-02 19:03
This is a duplicate of https://github.com/SumoLogic/js-logging-sdk/issues/28. Let's use that one.

**Closed by latkin** 2018-04-02 19:03 UTC
